---
tiers:
    -
        name: infra-healthcheck
        order: 1
        ci_loop: '(daily)|(weekly)!(gating)'
        description: >-
            Set of basic k8s Functional tests to validate the ONAP installation.
        testcases:
            -
                case_name: onap-k8s
                project_name: integration
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies that the ONAP pods are all Running
                    and shows the pods, deployments, svc and events
                run:
                    name: 'onap_k8s'
            -
                case_name: onap-helm
                project_name: integration
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies that the ONAP charts are in
                    DEPLOYED status
                run:
                    name: 'onap_helm'
            -
                case_name: nodeport_ingress
                project_name: security
                criteria: 100
                blocking: false
                description: >-
                    Check that there is no NodePort without corresponding
                    Ingress port
                dependencies:
                    - DEPLOY_SCENARIO: 'ingress'
                run:
                    name: 'nodeport_ingress'
            -
                case_name: nodeport_check_certs
                project_name: integration
                criteria: 100
                blocking: false
                description: >-
                    Check certificates associated with node ports
                run:
                    name: 'nodeport_check_certs'
            -
                case_name: onap-chart
                project_name: integration
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies that the ONAP pods are all Running
                    and shows the pods, deployments, svc and events for a
                    particular chart (SO, CLAMP, ...)
                dependencies:
                    - DEPLOY_ENVIRONMENT: 'gating_component'
                run:
                    name: 'onap_chart'
            -
                case_name: internal_check_certs
                project_name: integration
                criteria: 100
                blocking: false
                description: >-
                    Check certificates associated with internal ports
                dependencies:
                    - TEST_ENVIRONMENT: 'internal_job'
                run:
                    name: 'internal_check_certs'
