apiVersion: batch/v1
kind: Job
metadata:
    name: integration-onap-"{{ run_type }}"
    namespace: onap
spec:
    template:
        spec:
            containers:
            - env:
              - name: INSTALLER_TYPE
                value: "{{ deployment_name }}"
              - name: DEPLOY_SCENARIO
                value: "{{ deploy_scenario }}"
              - name: NODE_NAME
                value: "{{ node_name }}"
              - name: TEST_DB_URL
                value: http://testresults.opnfv.org/onap/api/v1/results
              - name: BUILD_TAG
                value: "{{ build_tag }}"
              - name: TAG
                value: "{{ run_type }}"
            image: nexus3.onap.org:10001/onap/xtesting-healthcheck:latest
            imagePullPolicy: Always
            name: integration-"{{ run_type }}"
            volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /share/config
              name: robot-eteshare
            - mountPath: /var/lib/xtesting/results/
              name: robot-save-results
            restartPolicy: Never
            volumes:
            - hostPath:
              path: /etc/localtime
              name: localtime
            - configMap:
                  defaultMode: 493
                  name: onap-robot-eteshare-configmap
              name: robot-eteshare
            - hostPath:
                  path: "{{ res_local_path }}"
              name: robot-save-results
