---
tiers:
    -
        name: smoke-usecases
        order: 1
        description: >-
            ONAP E2E tests
        testcases:
            -
                case_name: basic_vm
                project_name: integration
                enabled: true
                criteria: 100
                blocking: false
                description: >-
                    Onboard and instantiate a simple ubuntu16.04 VM VNF
                dependencies:
                run:
                    name: basic_vm
            -
                case_name: clearwater_ims
                project_name: integration
                enabled: true
                criteria: 100
                blocking: false
                description: >-
                    Onboard and instantiate a clearwater IMS VNF
                dependencies:
                run:
                    name: clearwater_ims
            -
                case_name: basic_network
                project_name: integration
                enabled: true
                criteria: 100
                blocking: false
                description: >-
                    Onboard and instantiate a basic network (ONAP VL)
                dependencies:
                run:
                    name: basic_network
            -
                case_name: basic_cnf
                project_name: integration
                enabled: true
                criteria: 100
                blocking: false
                description: >-
                    Onboard and instantiate a basic cnf (nginx in k8s namespace)
                dependencies:
                run:
                    name: basic_cnf
            -
                case_name: basic_cds
                project_name: integration
                enabled: true
                criteria: 100
                blocking: false
                description: >-
                    First basic test on CDS, including the creation of a Nodeport to expose
                    the CDS blueprint processor, bootstrap CDS blueprintprocessor, upload data
                    dictionnaire and enrich CBA file
                dependencies:
                run:
                    name: basic_cds
            -
                case_name: basic_onboard
                project_name: integration
                enabled: true
                criteria: 100
                blocking: false
                description: >-
                    Subset of basic_vm that performs only the onbaording part. A random service
                    name is created to be sure that all the onboard oiperations are performed
                    The main intereste is for stability tests, we can distinguish onboarding only and full tests.
                    First basic test on CDS, including the creation of a Nodeport to expose
                dependencies:
                run:
                    name: basic_onboard
