---
tiers:
    -
        name: benchmarking
        order: 1
        ci_loop: 'weekly'
        description: >-
            Set of basic Functional benchmarking tests.
        testcases:
            -
                case_name: stability72hr
                project_name: integration
                criteria: 100
                blocking: false
                description: >-
                    run stability 72h test.
                run:
                    name: 'robotframework'
                    args:
                        suites:
                            - /var/opt/ONAP/robot/testsuites/vnf-orchestration.robot
                        include:
                            - stability72hr
                        variablefile:
                            - '/share/config/robot_properties.py'
                            - '/share/config/integration_preload_parameters.py'
